#
# Flutter App CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  build:
    docker:
      - image: lathonez/ionic-android

    working_directory: /root/flutter-app

    steps:
      - checkout

      - restore_cache:
          keys:
          - npm-cache-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: agree to android license
          command: yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses || echo "0"

      - run:
          name: debug environment
          command: ionic info

      - run:
          name: Build
          # Ionic fails with a zero exit =)
          command: |
            ionic cordova build android --prod
            ls -l /root/flutter-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - store_artifacts:
          path: /root/flutter-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          destination: flutter-app.apk
