#
# Flutter App CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  build:
    docker:
      - image: agileek/ionic-framework

    working_directory: /root/flutter-app

    steps:
      - checkout

      - restore_cache:
          keys:
          - npm-cache-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: debug environment
          command: ionic info

      - run:
          name: Build
          command: |
            yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses
            ionic cordova build android

      - store_artifacts:
          path: /root/flutter-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          destination: flutter-app.apk
